Repository neg4n/next-api-og-image, pull requests merged in 2021-10, with the labels that each got.

#1 Create custom font loader utility
  example/pages/api/basic-custom-fonts.js
  src/index.ts
Labels: enhancement, hacktoberfest

#4 HTML Inspect in dev environment
  README.md
  src/index.ts
Labels: enhancement, hacktoberfest

#5 Add example usage of TailwindCSS with next-api-og-image
  README.md
  example/pages/api/basic-custom-fonts-local.js
  example/pages/api/basic-tailwind.js
  example/pages/api/basic-typescript.ts
Labels: documentation, enhancement, hacktoberfest

#17 Styled components example
  README.md
  example/package-lock.json
  example/package.json
  example/pages/api/basic-styled-components.js
Labels: documentation
